//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableProcessorWebApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>RussianpostSendingsStatus.dll</string>
  <string>CharectersConverter.dll</string>
  <string>GroupCounter.dll</string>
  <string>KladrImporter.dll</string>
  <string>SmartGroup.dll</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Modules {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Modules"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fn")]
        public string DownloadFileNameParamName {
            get {
                return ((string)(this["DownloadFileNameParamName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ex")]
        public string DownloadExtentionParamName {
            get {
                return ((string)(this["DownloadExtentionParamName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fnla")]
        public string DownloadFileAliasNameParamName {
            get {
                return ((string)(this["DownloadFileAliasNameParamName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/AddressesModel2.csdl|res://*/AddressesModel2.ssdl|res://*/AddressesModel2.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=WEBIIS\sqlexpress;Initial Catalog=KLADRDB;Persist Security Info=false;User ID=addressesreader;Password=Address2013;MultipleActiveResultSets=True&quot;")]
        public string AddressModel2Entities {
            get {
                return ((string)(this["AddressModel2Entities"]));
            }
        }
    }
}
