//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableProcessorNS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Excel Files;dbq=D:\\Projects\\TableProcessor\\TableProcessor\\TestData\\test.xlsx;" +
            "defaultdir=D:\\Projects\\TableProcessor\\TableProcessor\\TestData;driverid=1046;maxb" +
            "uffersize=2048;pagetimeout=5")]
        public string XLSX {
            get {
                return ((string)(this["XLSX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Excel Files;dbq=D:\\Projects\\TableProcessor\\TableProcessor\\TestData\\test.xls;d" +
            "efaultdir=D:\\Projects\\TableProcessor\\TableProcessor\\TestData;driverid=1046;maxbu" +
            "ffersize=2048;pagetimeout=5")]
        public string XLS {
            get {
                return ((string)(this["XLS"]));
            }
        }
    }
}
