//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1026.
// 
#pragma warning disable 1591

namespace TableProcessorNS.com.kayaposoft.Calendars {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="enricoBinding", Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class enrico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPublicHolidaysForMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPublicHolidaysForYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPublicHolidaysForDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback isPublicHolidayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSupportedCountriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public enrico() {
            this.Url = global::TableProcessorNS.Properties.Settings.Default.ImportCalendarsFromEnrico_com_kayaposoft_Calendars_enrico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPublicHolidaysForMonthCompletedEventHandler getPublicHolidaysForMonthCompleted;
        
        /// <remarks/>
        public event getPublicHolidaysForYearCompletedEventHandler getPublicHolidaysForYearCompleted;
        
        /// <remarks/>
        public event getPublicHolidaysForDateRangeCompletedEventHandler getPublicHolidaysForDateRangeCompleted;
        
        /// <remarks/>
        public event isPublicHolidayCompletedEventHandler isPublicHolidayCompleted;
        
        /// <remarks/>
        public event getSupportedCountriesCompletedEventHandler getSupportedCountriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.kayaposoft.com/enrico/ws/v1.0/#getPublicHolidaysForMonth", RequestNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", ResponseNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public PublicHolidayCollectionType getPublicHolidaysForMonth([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string month, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string year, string country, string region) {
            object[] results = this.Invoke("getPublicHolidaysForMonth", new object[] {
                        month,
                        year,
                        country,
                        region});
            return ((PublicHolidayCollectionType)(results[0]));
        }
        
        /// <remarks/>
        public void getPublicHolidaysForMonthAsync(string month, string year, string country, string region) {
            this.getPublicHolidaysForMonthAsync(month, year, country, region, null);
        }
        
        /// <remarks/>
        public void getPublicHolidaysForMonthAsync(string month, string year, string country, string region, object userState) {
            if ((this.getPublicHolidaysForMonthOperationCompleted == null)) {
                this.getPublicHolidaysForMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPublicHolidaysForMonthOperationCompleted);
            }
            this.InvokeAsync("getPublicHolidaysForMonth", new object[] {
                        month,
                        year,
                        country,
                        region}, this.getPublicHolidaysForMonthOperationCompleted, userState);
        }
        
        private void OngetPublicHolidaysForMonthOperationCompleted(object arg) {
            if ((this.getPublicHolidaysForMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPublicHolidaysForMonthCompleted(this, new getPublicHolidaysForMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.kayaposoft.com/enrico/ws/v1.0/#getPublicHolidaysForYear", RequestNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", ResponseNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public PublicHolidayCollectionType getPublicHolidaysForYear([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string year, string country, string region) {
            object[] results = this.Invoke("getPublicHolidaysForYear", new object[] {
                        year,
                        country,
                        region});
            return ((PublicHolidayCollectionType)(results[0]));
        }
        
        /// <remarks/>
        public void getPublicHolidaysForYearAsync(string year, string country, string region) {
            this.getPublicHolidaysForYearAsync(year, country, region, null);
        }
        
        /// <remarks/>
        public void getPublicHolidaysForYearAsync(string year, string country, string region, object userState) {
            if ((this.getPublicHolidaysForYearOperationCompleted == null)) {
                this.getPublicHolidaysForYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPublicHolidaysForYearOperationCompleted);
            }
            this.InvokeAsync("getPublicHolidaysForYear", new object[] {
                        year,
                        country,
                        region}, this.getPublicHolidaysForYearOperationCompleted, userState);
        }
        
        private void OngetPublicHolidaysForYearOperationCompleted(object arg) {
            if ((this.getPublicHolidaysForYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPublicHolidaysForYearCompleted(this, new getPublicHolidaysForYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.kayaposoft.com/enrico/ws/v1.0/#getPublicHolidaysForDateRange", RequestNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", ResponseNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public PublicHolidayCollectionType getPublicHolidaysForDateRange(DateType fromDate, DateType toDate, string country, string region) {
            object[] results = this.Invoke("getPublicHolidaysForDateRange", new object[] {
                        fromDate,
                        toDate,
                        country,
                        region});
            return ((PublicHolidayCollectionType)(results[0]));
        }
        
        /// <remarks/>
        public void getPublicHolidaysForDateRangeAsync(DateType fromDate, DateType toDate, string country, string region) {
            this.getPublicHolidaysForDateRangeAsync(fromDate, toDate, country, region, null);
        }
        
        /// <remarks/>
        public void getPublicHolidaysForDateRangeAsync(DateType fromDate, DateType toDate, string country, string region, object userState) {
            if ((this.getPublicHolidaysForDateRangeOperationCompleted == null)) {
                this.getPublicHolidaysForDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPublicHolidaysForDateRangeOperationCompleted);
            }
            this.InvokeAsync("getPublicHolidaysForDateRange", new object[] {
                        fromDate,
                        toDate,
                        country,
                        region}, this.getPublicHolidaysForDateRangeOperationCompleted, userState);
        }
        
        private void OngetPublicHolidaysForDateRangeOperationCompleted(object arg) {
            if ((this.getPublicHolidaysForDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPublicHolidaysForDateRangeCompleted(this, new getPublicHolidaysForDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.kayaposoft.com/enrico/ws/v1.0/#isPublicHoliday", RequestNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", ResponseNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public IsPublicHolidayType isPublicHoliday(DateType date, string country, string region) {
            object[] results = this.Invoke("isPublicHoliday", new object[] {
                        date,
                        country,
                        region});
            return ((IsPublicHolidayType)(results[0]));
        }
        
        /// <remarks/>
        public void isPublicHolidayAsync(DateType date, string country, string region) {
            this.isPublicHolidayAsync(date, country, region, null);
        }
        
        /// <remarks/>
        public void isPublicHolidayAsync(DateType date, string country, string region, object userState) {
            if ((this.isPublicHolidayOperationCompleted == null)) {
                this.isPublicHolidayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisPublicHolidayOperationCompleted);
            }
            this.InvokeAsync("isPublicHoliday", new object[] {
                        date,
                        country,
                        region}, this.isPublicHolidayOperationCompleted, userState);
        }
        
        private void OnisPublicHolidayOperationCompleted(object arg) {
            if ((this.isPublicHolidayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isPublicHolidayCompleted(this, new isPublicHolidayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.kayaposoft.com/enrico/ws/v1.0/#getSupportedCountries", RequestNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", ResponseNamespace="http://www.kayaposoft.com/enrico/ws/v1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SupportedCountriesType getSupportedCountries() {
            object[] results = this.Invoke("getSupportedCountries", new object[0]);
            return ((SupportedCountriesType)(results[0]));
        }
        
        /// <remarks/>
        public void getSupportedCountriesAsync() {
            this.getSupportedCountriesAsync(null);
        }
        
        /// <remarks/>
        public void getSupportedCountriesAsync(object userState) {
            if ((this.getSupportedCountriesOperationCompleted == null)) {
                this.getSupportedCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSupportedCountriesOperationCompleted);
            }
            this.InvokeAsync("getSupportedCountries", new object[0], this.getSupportedCountriesOperationCompleted, userState);
        }
        
        private void OngetSupportedCountriesOperationCompleted(object arg) {
            if ((this.getSupportedCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSupportedCountriesCompleted(this, new getSupportedCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class PublicHolidayCollectionType {
        
        private string errorField;
        
        private PublicHolidayType[] publicHolidaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publicHolidays", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublicHolidayType[] publicHolidays {
            get {
                return this.publicHolidaysField;
            }
            set {
                this.publicHolidaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class PublicHolidayType {
        
        private DateType dateField;
        
        private string localNameField;
        
        private string englishNameField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DateType date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localName {
            get {
                return this.localNameField;
            }
            set {
                this.localNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string englishName {
            get {
                return this.englishNameField;
            }
            set {
                this.englishNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class DateType {
        
        private int dayField;
        
        private int monthField;
        
        private int yearField;
        
        private int dayOfWeekField;
        
        private bool dayOfWeekFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dayOfWeek {
            get {
                return this.dayOfWeekField;
            }
            set {
                this.dayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dayOfWeekSpecified {
            get {
                return this.dayOfWeekFieldSpecified;
            }
            set {
                this.dayOfWeekFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class SupportedCountryType {
        
        private string fullNameField;
        
        private string countryCodeField;
        
        private DateType fromDateField;
        
        private DateType toDateField;
        
        private string[] regionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DateType fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DateType toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] regions {
            get {
                return this.regionsField;
            }
            set {
                this.regionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class SupportedCountriesType {
        
        private string errorField;
        
        private SupportedCountryType[] supportedCountriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supportedCountries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SupportedCountryType[] supportedCountries {
            get {
                return this.supportedCountriesField;
            }
            set {
                this.supportedCountriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kayaposoft.com/enrico/ws/v1.0/")]
    public partial class IsPublicHolidayType {
        
        private string errorField;
        
        private bool isPublicHolidayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isPublicHoliday {
            get {
                return this.isPublicHolidayField;
            }
            set {
                this.isPublicHolidayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPublicHolidaysForMonthCompletedEventHandler(object sender, getPublicHolidaysForMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPublicHolidaysForMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPublicHolidaysForMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublicHolidayCollectionType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublicHolidayCollectionType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPublicHolidaysForYearCompletedEventHandler(object sender, getPublicHolidaysForYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPublicHolidaysForYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPublicHolidaysForYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublicHolidayCollectionType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublicHolidayCollectionType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPublicHolidaysForDateRangeCompletedEventHandler(object sender, getPublicHolidaysForDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPublicHolidaysForDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPublicHolidaysForDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublicHolidayCollectionType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublicHolidayCollectionType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void isPublicHolidayCompletedEventHandler(object sender, isPublicHolidayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isPublicHolidayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isPublicHolidayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IsPublicHolidayType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IsPublicHolidayType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSupportedCountriesCompletedEventHandler(object sender, getSupportedCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSupportedCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSupportedCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SupportedCountriesType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SupportedCountriesType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591